import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-[#020202] text-zinc-300 min-h-screen flex items-center justify-center overflow-hidden selection:bg-green-500/30 selection:text-green-200 antialiased`}>
        <main className="relative z-10 w-full max-w-[420px] px-6">
          {children}
        </main>
        <div className="fixed inset-0 pointer-events-none">
          <div className="absolute top-1/2 left-1/3 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-green-500/20 rounded-full blur-[128px] opacity-60"></div>
          <div className="absolute top-1/2 right-1/3 translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-fuchsia-600/15 rounded-full blur-[128px] opacity-60"></div>
        </div>
      </body>
    </html>
  );
}
