import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import "../globals.css";
import { requireAdmin } from "@/shared/auth/guards";
import { ToastHandler } from "@/components/base/toast-handler";
import { Toaster } from "sonner";
import { getUserSession } from "@/shared/auth/session";
import { Sidebar } from "@/widgets/admin/sidebar";
import { Header } from "@/widgets/admin/header";
import { usersService } from "@/entities/users/users.service";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Панель администратора",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await requireAdmin();
  const session = await getUserSession();
  let currentUser = null;
  if (session?.userId) {
    try {
      currentUser = await usersService.getMe();
    } catch (error) {
      console.error("Пользователь не найден ", error);
    }
  }
  const user = currentUser.data;
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable} dark bg-[#050505] text-zinc-400 h-screen w-screen overflow-hidden flex selection:bg-rose-500/30 selection:text-rose-200 antialiased`}>
        <NuqsAdapter>
          <Sidebar timer={session?.sessionStart} />
          <div className="relative z-10 flex-1 flex flex-col overflow-hidden">
            <Header user={user} />
            <main className="p-10 w-full overflow-y-scroll">
              {children}
            </main>
          </div>
          <ToastHandler />
          <Toaster position="bottom-right" richColors />
          <div className="fixed top-[-10%] left-[-10%] w-[60%] h-[60%] bg-rose-950/30 rounded-full blur-[150px] pointer-events-none z-0 mix-blend-screen"></div>
          <div className="fixed bottom-[-10%] right-[-5%] w-[50%] h-[60%] bg-zinc-800/20 rounded-full blur-[120px] pointer-events-none z-0"></div>
          <div className="fixed top-[20%] right-[20%] w-[30%] h-[30%] bg-[#2a0a0a] rounded-full blur-[100px] pointer-events-none z-0"></div>
        </NuqsAdapter>
      </body>
    </html>
  );
}
