import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { getUserSession } from "@/shared/auth/session";
import { Header } from "@/widgets/public/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserSession();
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-[#020001] text-zinc-300 overflow-x-hidden min-h-screen relative selection:bg-red-500/30 selection:text-red-200 flex flex-col antialiased`}>
        <Header user={user} />
        <main className="relative z-10 flex-grow flex flex-col items-center justify-center px-6 pt-32 pb-20">
        {children}
        </main>
        <div className="fixed top-0 left-0 w-full h-full overflow-hidden -z-10 pointer-events-none">
          <div className="absolute top-[-20%] left-[20%] right-[20%] h-[60%] rounded-full bg-red-600/20 blur-[120px]"></div>
          <div className="absolute bottom-[-10%] left-[-10%] w-[50%] h-[50%] rounded-full bg-rose-900/30 blur-[130px]"></div>
          <div className="absolute bottom-[10%] right-[-10%] w-[40%] h-[50%] rounded-full bg-red-500/10 blur-[100px]"></div>
        </div>
      </body>
    </html>
  );
}
